export default {
    GET_DRIVERS: "GET_DRIVERS",
    GET_DRIVERS_SUCCESS: "GET_DRIVERS_SUCCESS",
    DRIVER_BOOKING: "DRIVER_BOOKING",
    GET_DRIVER_BOOKINGS: "GET_DRIVER_BOOKINGS",
    GET_DRIVER_BOOKINGS_SUCCESS: "GET_DRIVER_BOOKINGS_SUCCESS",
    UPDATE_DRIVER_STATUS: "UPDATE_DRIVER_STATUS",
    MAKE_DRIVER_AVAILABLE: "MAKE_DRIVER_AVAILABLE",
}