export default {
REGISTER_VEHICLE : "REGISTER_VEHICLE",
GET_VEHICLES : "GET_VEHICLES",
GET_VEHICLES_SUCCESS: "GET_VEHICLES_SUCCESS",
TRANSPORTER_BOOKINGS: "TRANSPORTER_BOOKINGS",
TRANSPORTER_BOOKINGS_SUCCESS: "TRANSPORTER_BOOKINGS_SUCCESS",
DELETE_VEHICLE: "DELETE_VEHICLE",
}