/* eslint-disable react/no-unknown-property */
/* eslint-disable @next/next/no-sync-scripts */
import "../styles/globals.css";
import "../styles/vehicles.css";
import Navbar from "../components/Nav";
import Footer from "../components/Footer";
import Head from "next/head";
import { ReduxWrapper } from "../redux/store";
import Script from "next/script";
import Layout from "../components/Layout";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Easy Transport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default ReduxWrapper.withRedux(MyApp);
